### ISSUE TITLE
Alternative ways to make omnibox dark?

### ISSUE THREAD

**Issue by poma** [Fiddle-N/material-incognito-dark-theme#1]
Maybe there are other ways to make omnibox dark except making a Windowblinds theme? It takes its color settings from windows, so changing high contrast colors changes it to dark (but makes other apps look awful). Maybe there is a way to apply high contrast settings to only chrome process? Even is an additional app is required I think this could be very useful.

Also we can create a request to make omnibox themeable and link it in theme description.

**Comment by Fiddle-N** [comment]
I appreciate your suggestions. However, I think what you are suggesting wrt creating a program to apply high contrast to Chrome only is pretty difficult to do. Creating a request for the Chrome devs is a good idea though, I may look to doing that.

**Comment by iwsfg** [comment]
>  except making a Windowblinds theme? It takes its color settings from windows

It used to in the old UI, but it doesn't seem to be the case with the new one. I have themed Windows 7 and old ui inherits dark scheme just fine. New UI (in Chrome Canary at least) forces it to be white when browser theme is installed. Can't believe they hardcoded it

old w/ theme:
![image](https://user-images.githubusercontent.com/5304842/45955329-e1321b80-c00f-11e8-9294-49b5007e8664.png)
new w/o theme:
![image](https://user-images.githubusercontent.com/5304842/45954601-be066c80-c00d-11e8-8c2b-e58bb7dd50fe.png)
new w/ theme
![image](https://user-images.githubusercontent.com/5304842/45954681-eee6a180-c00d-11e8-8da6-795ec7266423.png)

I guess I'll be staying away from new design after all. Context menus also look ridiculous in the new one

**Comment by iwsfg** [comment]
So I got curious and tried to look at the Chromium source code. Found [this function][omnibox-get-tint-function], they actually hardcoded it. It has a TODO comment about determining omnibox tint from theme, but it's been there [for over 7 months already][omnibox-tint-commit] and is probably long forgotten. 

I suggest we look for an issue about this on chrome issue tracker or create a new one if it does not exists, post a link in this issue and ask people to star it to show their interest. And I'd also suggest reopening this issue but maybe labeling it as blocked for better visibility. It's clear that here's some interest in this.

In the meantime the only way to get dark omnibox with custom theme is to use GTK environment.

/cc @Fiddle-N 

[omnibox-get-tint-function]: https://cs.chromium.org/chromium/src/chrome/browser/ui/views/location_bar/location_bar_view.cc?l=1038-1053&rcl=b47bb9f8db4b3275d13cc85b6858ae3be1fbdfb7
[omnibox-tint-commit]: https://chromium.googlesource.com/chromium/src/+/b590a586469bca028bc7770f6c9bad066a6c8dad%5E%21/chrome/browser/ui/views/location_bar/location_bar_view.cc

**Comment by Fiddle-N** [comment]
Some links that show the Chrome team are thinking about this:
https://bugs.chromium.org/p/chromium/issues/detail?id=838670
https://www.reddit.com/r/chrome/comments/9hqvh0/_/e6dxnsm

I won't reopen this issue because it's not so much an issue as a question. But if you want to add an issue such as "Omnibox colouring" I'm happy to keep it open and marked as blocked.

**Comment by iwsfg** [comment]
Well, that's reassuring. 

Personally I would prefer if it also was customizable via theme's manifest as well – white omnibox sticks out way too much on many dark themes (and because I'm a stubborn Windows 7 user that wouldn't get dark omnibox otherwise). I should suggest that in a comment on that issue from chrome's bug tracker you linked.

Thanks for replying!
