### ISSUE TITLE
Make this dark theme same as Inspector's dark theme

### ISSUE THREAD

**Issue by iegik** [Fiddle-N/material-incognito-dark-theme#10]
![](http://snappyimages.nextwavesrl.netdna-cdn.com/img/de6dcd93be65034d0db6e0af1d60ad32.png)
http://snpy.in/hEPy3r

**Comment by Fiddle-N** [comment]
My theme has a very clear purpose - to replicate the incognito dark theme across normal mode. You are, of course, more than welcome to fork my theme and create your own based off of the developer tools. However, I'm not going to change my theme just to accommodate your suggestion.
