### ISSUE TITLE
No text after installing theme

### ISSUE THREAD

**Issue by Eldenroot** [Fiddle-N/material-incognito-dark-theme#12]
![image](https://user-images.githubusercontent.com/778890/45927851-356acc00-bf3a-11e8-90b3-379e89d05a14.png)

**Comment by Fiddle-N** [comment]
Sorry but it looks fine for me. 

![image](https://user-images.githubusercontent.com/20640528/45930254-ac618e00-bf55-11e8-81fa-b04d4bbaa33b.png)
