### ISSUE TITLE
Colour on the google text

### ISSUE THREAD

**Issue by mrthordavis** [Fiddle-N/material-incognito-dark-theme#15]
Would it be possible to add colour to the google logo on the main startscreen, kinda [Like this](https://ibb.co/fgtEsf)? This would make the theme look awesome.

**Comment by Fiddle-N** [comment]
Yes, it's possible. Theme devs are allowed to choose which version of the Google logo they want to use. However, I prefer a white Google logo on a grey background; I think that it looks cleaner. I will not be changing the theme, but you are more than welcome to fork the theme and change the Google logo yourself.
