### ISSUE TITLE
Dark URL Bar?

### ISSUE THREAD

**Issue by Nou4r** [Fiddle-N/material-incognito-dark-theme#16]
Is it possible to make the URL Bar dark just like in the incognito mode?

Awesome job btw.

**Comment by Nou4r** [comment]
https://github.com/Fiddle-N/material-incognito-dark-theme/issues/5
Is it really impossible?

**Comment by Fiddle-N** [comment]
Chrome theme devs currently have no ability to colour the omnibox. As a result, the omnibox will always be white.

**Comment by Eangmony77** [comment]
#16
