### ISSUE TITLE
Chrome apps still white.

### ISSUE THREAD

**Issue by jgatlan** [Fiddle-N/material-incognito-dark-theme#18]
When you open a chrome app in a separate window the title bar of the window is still white, can you change this?
Open chrome://apps/, right click an app, enable "Open as window" and then open it to see what I mean.
![image](https://user-images.githubusercontent.com/28867024/53162661-c8cd2980-35cc-11e9-93c6-0dd036caefeb.png)

**Comment by Fiddle-N** [comment]
Can't be changed; Google doesn't want themes to be able to colour app titlebars.

**Comment by ngouy** [comment]
I guess same fight for chrome://settings for exemple ?

**Comment by Fiddle-N** [comment]
chrome://settings isn't in its own window, so doesn't have its own titlebar like Chrome apps and extensions.
