### ISSUE TITLE
White line above url bar still present in Chrome 61

### ISSUE THREAD

**Issue by hpohlmeyer** [Fiddle-N/material-incognito-dark-theme#2]
The readme says the white line above the url bar should be fixed but I can still see it.

Mac OS High Sierra (10.13)  
Chrome Version 61.0.3163.100 (Official Build) (64-bit)

![screen shot 2017-10-13 at 22 47 22](https://user-images.githubusercontent.com/6564077/31565985-209f83dc-b069-11e7-89e3-b850db52b8da.png)

**Comment by Fiddle-N** [comment]
I was previously referring to an issue on Windows 10. Sorry, I can't do anything about debugging issues on macOS as I do not own any Mac computers.
