### ISSUE TITLE
Minor black-on-black text issue

### ISSUE THREAD

**Issue by AndhikaWB** [Fiddle-N/material-incognito-dark-theme#4]
I think the 'Gmail' and 'Images' text should to be white instead of black. Is this an issue with Google itself or the theme?
![screenshot_1](https://user-images.githubusercontent.com/17119394/42124719-65f6677a-7c92-11e8-826e-3f3b4ba1865d.png)

**Comment by AndhikaWB** [comment]
Tested on Chromium on Windows 10 v67.0.3396.99

**Comment by Fiddle-N** [comment]
Looks fine to me on Google Chrome Windows 10 v67.0.3396.87. The only thing I can suggest is installing/reinstalling the theme.

![image](https://user-images.githubusercontent.com/20640528/42124870-bb13e47e-7c62-11e8-9daa-3cec760fdf0d.png)

**Comment by AndhikaWB** [comment]
Hmm.. still no change. I even deleted the entire Chromium data folder. I don't think it's because of my uBlock Origin because it doesnt even enable itself on new tab page. I don't have any other extension by the way.

Installed Chromium from [chromium.woolyss.com](https://github.com/henrypp/chromium/releases/download/v67.0.3396.99-r550428-win64/chromium-nosync.zip).

**Comment by Fiddle-N** [comment]
I have uBlock and it works just fine. I don't know what else to suggest really other than a full uninstall/reinstall of Chromium.
