### ISSUE TITLE
Bookmark folder icon invisible

### ISSUE THREAD

**Issue by GeitHub** [Fiddle-N/material-incognito-dark-theme#6]
Bug that I noticed: (with the exception of the bookmark bar) folder icons aren't visible.

To reproduce:
1. Create a folder
2. Create a folder inside that folder

The second folder's icon is invisible.

(also, unrelated but I noticed the new update makes incognito mode's URL bar white whereas in the old version the incognito mode would remain dark regardless of theme)

**Comment by Fiddle-N** [comment]
Can you send a screenshot? I'm having trouble reproducing this.

**Comment by GeitHub** [comment]
<img width="355" alt="screen shot 2018-09-07 at 12 07 42 pm" src="https://user-images.githubusercontent.com/19231670/45232942-d6992780-b296-11e8-9f00-6b9e8dba7d2a.png">

**Comment by GeitHub** [comment]
I'm on the latest stable Chrome and latest macOS btw

**Comment by Fiddle-N** [comment]
So, this is only an issue on macOS. On Windows 10, the folder is a yellow icon and is not dynamically generated, so it doesn't have this problem.

Is this only an issue for the folder icon? Can you try the same with other pages that have dynamically-coloured icons, such as the settings page or the extensions page, and report back if you have the same issue?

**Comment by kytosai** [comment]
I have same issue on Chrome 69 MacOS 10.13.6 
Demo: http://prntscr.com/ks3g5e

**Comment by Fiddle-N** [comment]
That's not what I meant, I meant something like this:

![image](https://user-images.githubusercontent.com/20640528/45594257-64f46400-b98f-11e8-98c3-a61755c53dca.png)

So I can compare Windows 10 vs macOS on how favicons look within nested folders.

**Comment by GeitHub** [comment]
<img width="125" alt="screen shot 2018-09-17 at 1 49 29 am" src="https://user-images.githubusercontent.com/19231670/45609082-01fcde80-ba1c-11e8-989e-32780ff8724d.png">

**Comment by mmakarios** [comment]
I'm using Chrome's Dev channel and I think they fixed this in the last update.
It was happening in the official Incognito mode and now the folder icon is there.

**Comment by Fiddle-N** [comment]
@mmakarios, could you install my theme and check in Chrome Dev to see if this is fixed? If so, I'll feel confident enough to close this out.

**Comment by mmakarios** [comment]
Forgot to mention that I already use your theme. Yes, it is fixed!

**Comment by Fiddle-N** [comment]
Great, I'll mark this as closed then.
