### ISSUE TITLE
Chrome OS Issues

### ISSUE THREAD

**Issue by GeitHub** [Fiddle-N/material-incognito-dark-theme#8]
![screenshot 2018-09-17 at 2 01 30 am](https://user-images.githubusercontent.com/19231670/45609528-fc07fd00-ba1d-11e8-9fab-09f680ec97eb.png)

![screenshot 2018-09-17 at 2 02 24 am](https://user-images.githubusercontent.com/19231670/45609534-01fdde00-ba1e-11e8-9d61-3f993f60be5e.png)

Newest version of ChromeOS, the tab should be dark.

Also, the buttons are the incorrect shade of white.

**Comment by Fiddle-N** [comment]
This looks very much like you are using v68 of Chrome OS with the incomplete redesign. Please confirm the version of Chrome OS here.

**Comment by GeitHub** [comment]
Sorry, it's the most updated version of ChromeOS for me, but it's Chrome 68 lol.
