### ISSUE TITLE
Tabs are white instead of dark

### ISSUE THREAD

**Issue by obahareth** [Fiddle-N/material-incognito-dark-theme#9]
I just tried installing this theme on macOS (I'm on the latest beta of Mojave, this could be the reason), and my tabs are white instead of dark.

What the Chrome Webstore shows tabs looking like:
![](https://lh3.googleusercontent.com/QwQ2yuLPEcgE8_DT-Y6wdbXFyBHhrzgiqPAXSuZVMBf-jBP8IM3pl2BtWjwaZDLKHGVTaKMY=w640-h400-e365)

What I see:
<img width="1242" alt="screenshot 2018-09-19 11 17 25" src="https://user-images.githubusercontent.com/3428118/45740315-aa1dcd80-bbfd-11e8-80a6-93b5da5039aa.png">

**Comment by Fiddle-N** [comment]
You are using Chrome v68. Please upgrade to v69.

**Comment by obahareth** [comment]
You are totally right (I'm sorry), I was using Chrome 68 with the material design enabled (thinking that it auto-upgraded to Chrome 69) and I thought it'd work. My bad.
